

###############################################################
#------------------------------------------------------------ #
#     _____             _  _____ _       _                    #
#    / ____|           | |/ ____(_)     | |                   #
#   | (___   ___  _   _| | (___  _ _ __ | |__   ___  _ __     #
#    \___ \ / _ \| | | | |\___ \| | '_ \| '_ \ / _ \| '_ \    #
#    ____) | (_) | |_| | |____) | | |_) | | | | (_) | | | |   #
#   |_____/ \___/ \__,_|_|_____/|_| .__/|_| |_|\___/|_| |_|   #
#                                 | |                         #
#                                 |_|                         #
#-------------------------------------------------------------#
###############################################################



#Before you reset all players health, make sure to reset your world and inventories first to protect against heart-duping!

#Keeps track of whether certain functions have been run before. Do not touch unless you know what you are doing!
HBR: false
HBRB: false
HBRC: false

##############################
#	    Heart Modifiers      #
##############################

#Base health is 10 hearts. use negative numbers to lower the starting health. Default: 0
StartingHeartsModifier: 0

#Should players lose hearts to non-player causes? Default: true
OtherDeathsCount: true

#Number of hearts to remove on death. Default: 1
HeartsLostOnDeath: 1

#Should hearts drop on death? If true, a heart item will drop. If false, the heart will automatically go to the killer. HeartsEnabled must be set to true. Default: false
HeartsDropOnDeath: false

#Should hearts drop from non-player deaths? HeartsEnabled and HeartsDropOnDeath must be set to true. Default: false
OtherDeathsDrop: false

#Should players be able to craft vanilla beacons (NOT REVIVE) with hearts? Only enable if you know what you are doing! Default: false
CraftBeaconWithHearts: false

#Should hearts drop to the ground if the withdraw command is used while their inventory is full? CanWithdraw must be set to true. Default: true
HeartDropsIfFull: true

#########################
#	   Heart Items 	    #
#########################


#Are heart items enabled? Default: true
HeartsEnabled: true

#Is the heart recipe enabled? HeartsEnabled must be set to true. Default: true
HeartRecipeEnabled: true

#Name of hearts.
HeartName: "Heart"

#Heart lore. Up to three lines.
HeartLore:
  - "Use this to increase your hearts!"
  - ""
  - ""

#Custom crafting recipe for hearts.
#Sets the values of keys within the crafting recipe. This will automatically update. Requires a full server restart. E is missing due to event handling.
CRKeys:
  a: "DIAMOND"
  b: "TOTEM_OF_UNDYING"
  c: 3
  d: 4
  f: 5
  g: 6
  h: 7
  i: 8
  j: 9

#########################
#      Beacon Items	    #
#########################

#Are beacon items enabled? Default: true
BeaconsEnabled: true

#Name of beacons.
BeaconName: "Beacon"

#Beacon lore. Up to three lines.
BeaconLore:
  - "Use this item to revive a lost soul."
  - ""
  - ""

#Custom crafting recipe for revive beacons.
#Sets the values of keys within the crafting recipe. This will automatically update. Requires a full server restart. E is missing due to event handling.
#Use "Heart" to use a heart item in the recipe.
CRKeysB:
  a: "DIAMOND"
  b: "TOTEM_OF_UNDYING"
  c: "Heart"
  d: 4
  f: 5
  g: 6
  h: 7
  i: 8
  j: 9

#################################
#	    Gameplay Settings	    #
#################################

#Should players be banned, put in spectator, or put in adventure mode when they run out of hearts? Default: spectator
#Players who are put in adventure mode may be able to obtain new hearts!
#Perameters: spectator, adventure, banned.
DeathOutcome: "spectator"

#Can players use the /withdraw command? HeartsEnabled must be set to true. Default: true
CanWithdraw: true

#Should enderchest be reset when a player completely dies? Default: true
EnderchestOnLoss: true

#World spawnpoint where revived players will spawn.
#Make sure to set this, as it does not check for safety.
#This does not set the worldspawn, just where players who were revived will be spawned so that they don't spawn where they last were.
ReviveSpawn:
  world: world
  x: 0
  y: 60
  z: 0

#Should players be able to use the leaderboard command? default: true
LeaderboardEnabled: true

#Number of spots on the leaderboard
LeaderboardSpots: 10

###############################
#	    Admin Settings        #
###############################

#Default message prefix.
Prefix: "[SoulSiphon]"

#Should players be completely reset if /resetlives is used on them and they are still alive? This will affect inventory, location, experience, and enderchests. Default: true
FullResetCommand: true


#############################
#	    Death Message       #
#############################

#Is the final death message enabled? Default: true
DeathMessageEnabled: true

##################
#     Effects	 #
##################

#Should consuming a heart produce particles/sounds? default: true
HeartUseParticles: true
HeartParticleCount: 25
HeartUseSounds: true

#Should consuming a revive beacon produce particles/sounds? default: true
BeaconUseParticles: true
BeaconUseSounds: true
BeaconUseMusic: true

#Should dying to another player produce particles? default: true
DeathParticles: true

#Should dying to a non-player source produce particles? default: true
OtherDeathParticles: true

#Number of particles to produce upon death.
DeathParticlesCount: 25