name: SoulSiphon
version: '1.2'
main: com.dop.soulsiphon.Main
api-version: '1.20'
author: DaysOfPeace
commands:
  withdraw:
    description: "Withdraws a life!"
  resetlives:
    description: "Resets the lives of all dead players!"
  setrevivespawn:
    description: "Sets the revive spawn to where you are standing!"
  soulsiphon:
